//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verkoop.CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCompra()
        {
            this.tblProductoComprado = new HashSet<tblProductoComprado>();
        }
    
        public int iIdCompra { get; set; }
        public int iIdUsuario { get; set; }
        public int iIdDireccion { get; set; }
        public Nullable<System.DateTime> dtFecha { get; set; }
    
        public virtual tblCat_Usuario tblCat_Usuario { get; set; }
        public virtual tblDireccion tblDireccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductoComprado> tblProductoComprado { get; set; }
    }
}
