//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verkoop.CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCarrito
    {
        public int iIdCarrito { get; set; }
        public int iIdUsuario { get; set; }
        public int iIdProducto { get; set; }
        public bool lEstatus { get; set; }
        public System.DateTime dtFechaSeleccion { get; set; }
    
        public virtual tblCat_Producto tblCat_Producto { get; set; }
        public virtual tblCat_Usuario tblCat_Usuario { get; set; }
    }
}
