//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verkoop.CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDireccion
    {
        public int iIdDireccion { get; set; }
        public int iIdUsuario { get; set; }
        public int iIdMunicipio { get; set; }
        public string cDireccion { get; set; }
        public string cCodigoPostal { get; set; }
        public bool lDefault { get; set; }
    }
}
