//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verkoop.CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDireccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDireccion()
        {
            this.tblCompra = new HashSet<tblCompra>();
        }
    
        public int iIdDireccion { get; set; }
        public int iIdUsuario { get; set; }
        public int iIdMunicipio { get; set; }
        public string cDireccion { get; set; }
        public string cCodigoPostal { get; set; }
        public bool lDefault { get; set; }
    
        public virtual tblCat_Usuario tblCat_Usuario { get; set; }
        public virtual tblMunicipio tblMunicipio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCompra> tblCompra { get; set; }
    }
}
