//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verkoop.CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSesion
    {
        public int iIdSesion { get; set; }
        public int iIdUsuario { get; set; }
        public string cCorreo { get; set; }
        public string cContrasenia { get; set; }
        public Nullable<System.DateTime> dtFechaActualizacion { get; set; }
        public string cCodigoVerificacion { get; set; }
        public bool lEstadoVerificacion { get; set; }
    
        public virtual tblCat_Usuario tblCat_Usuario { get; set; }
    }
}
