//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verkoop.CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTarjeta
    {
        public int iIdTarjeta { get; set; }
        public int iIdUsuario { get; set; }
        public string cNumeroTarjeta { get; set; }
        public string cMesVigencia { get; set; }
        public string cAnioVigencia { get; set; }
    
        public virtual tblCat_Usuario tblCat_Usuario { get; set; }
    }
}
