//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verkoop.CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTarjeta
    {
        public int iIdTarjeta { get; set; }
        public int iIdUsuario { get; set; }
        public string cNumeroTarjeta { get; set; }
        public string cMesVigencia { get; set; }
        public string cAnioVigencia { get; set; }
        public bool lDefault { get; set; }
    
        public virtual tblCat_Usuario tblCat_Usuario { get; set; }
    }
}
