//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verkoop.CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValoracion
    {
        public int iIdValoracion { get; set; }
        public int iIdUsuario { get; set; }
        public int iIdProducto { get; set; }
        public Nullable<System.DateTime> dtFecha { get; set; }
    
        public virtual tblCat_Producto tblCat_Producto { get; set; }
        public virtual tblCat_Usuario tblCat_Usuario { get; set; }
    }
}
