//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verkoop.CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VerkoopDBEntities : DbContext
    {
        public VerkoopDBEntities()
            : base("name=VerkoopDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCarrito> tblCarrito { get; set; }
        public virtual DbSet<tblCat_Categoria> tblCat_Categoria { get; set; }
        public virtual DbSet<tblCat_Producto> tblCat_Producto { get; set; }
        public virtual DbSet<tblCat_Usuario> tblCat_Usuario { get; set; }
        public virtual DbSet<tblDireccion> tblDireccion { get; set; }
        public virtual DbSet<tblEstado> tblEstado { get; set; }
        public virtual DbSet<tblMunicipio> tblMunicipio { get; set; }
        public virtual DbSet<tblPais> tblPais { get; set; }
        public virtual DbSet<tblProductoComprado> tblProductoComprado { get; set; }
        public virtual DbSet<tblTarjeta> tblTarjeta { get; set; }
        public virtual DbSet<tblComentario> tblComentario { get; set; }
        public virtual DbSet<tblValoracion> tblValoracion { get; set; }
        public virtual DbSet<tblSesion> tblSesion { get; set; }
        public virtual DbSet<tblCompra> tblCompra { get; set; }
    }
}
